[workspace]
resolver = "3"
members = [ "agent-interface", "cgroup_manager","server"]
# exclude = [ "server/tests/**" ]
# EXCLUDE DOES NOT WORK ! MUST add "[workspace]" (empty) in the other's cargo.toml !
